<program>     ::= <statement>* EOF ;

<declaration> ::= <class-decl> | <fun-decl> | <var-decl> | <statement>;
<class-decl>  ::= "class" IDENTIFIER ( "<" IDENTIFIER )? "{" <function>*  "}" ;
<fun-decl>    ::= "fun" <function> ;
<parameters>  ::= IDENTIFIER ( "," IDENTIFIER )* ;
<var-decl>   ::= "var" IDENTIFIER ( "=" <expression> )? ";" ;
<function>   ::= IDENTIFIER "(" <parameters>? ")" <block> ;

<statement>   ::= <expr-stmt>
                | <print-stmt>
                | <block>
                | <if-stmt>
                | <while-stmt>
                | <for-stmt>
                | <return-stmt> ;
<block>       ::= "{" <declaration>* "}" ;
<expr-stmt>    ::= <expression> ";" ;
<print-stmt>   ::= "print" <expression> ";" ;
<if-stmt>      ::= "if" "(" <expression> ")" <statement> ( "else" <statement> )? ;
<while-stmt>   ::= "while" "(" <expression> ")" <statement> ;
<for-stmt>     ::= "for" "(" ( <var-decl> | <expr-stmt> | ";" )
                    <expression>? ";"
                    <expression>? ")" <statement> ;
<return-stmt>  ::= "return" <expression>? ";" ;

<expression>  ::= <assignment> ;
<assignment>  ::= (call "." )? IDENTIFIER "=" <assignment>
                | <logic-or> ;
<logic-or>    ::= <logic-or> ( "or" <logic-and> )* ;
<logic-and>   ::= <equality> ( "and" <equality> )* ;
<equality>    ::= <comparison> ( ( "!=" | "==" ) <comparison> )* ;
<comparison>  ::= <term> ( ( ">" | ">=" | "<" | "<=" ) <term> )* ;
<term>        ::= <factor> ( ( "-" | "+" ) <factor> )* ;
<factor>      ::= <unary> ( ( "/" | "*" ) <unary> )* ;
<unary>       ::= ( "!" | "-" ) <unary>
                | call ;
<call>        ::= primary ( "(" arguments? ")" | "." IDENTIFIER )* ;
<primary>     ::= NUMBER | STRING | "true" | "false" | "nil"
                | "(" expression ")"
                | "this"
                | "super" "." IDENTIFIER
                | IDENTIFIER ;
